name: dfxai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp=3.9.3=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aom=3.6.0=h6a678d5_0
  - arrow-cpp=14.0.2=h374c478_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py310h06a4308_0
  - attrs=23.1.0=py310h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310h6a678d5_7
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310h06a4308_0
  - cloudpickle=2.2.1=py310h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py310h06a4308_0
  - cryptography=41.0.7=py310hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cytoolz=0.12.2=py310h5eee18b_0
  - dask-core=2023.11.0=py310h06a4308_0
  - datasets=2.12.0=py310h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.6=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py310h5eee18b_0
  - fsspec=2023.12.2=pyhca7485f_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.1=h5eee18b_3
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - huggingface_hub=0.17.3=py310h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py310h06a4308_0
  - imagecodecs=2023.1.23=py310hc4b7b5f_0
  - imageio=2.31.4=py310h06a4308_0
  - importlib-metadata=7.0.1=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=py310h06a4308_0
  - ipython=8.20.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py310h06a4308_0
  - jupyter_core=5.5.0=py310h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.3=py310h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libavif=0.11.1=h5eee18b_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_4
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.2.0=h807b86a_4
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libzopfli=1.0.3=he6710b0_0
  - lightning=2.1.3=pyhd8ed1ab_1
  - lightning-utilities=0.10.1=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - locket=1.0.0=py310h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.0.4=py310h5eee18b_0
  - multiprocess=0.70.14=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.3=py310h5f9d8c6_0
  - numpy-base=1.26.3=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py310h06a4308_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3.1=py310h06a4308_0
  - platformdirs=3.10.0=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=14.0.2=py310h1eedbd7_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.11=h955ad1f_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py310h5eee18b_1
  - pytorch=2.2.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=2.1.3=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.5.0=py310ha9d4c09_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py310h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - responses=0.13.3=pyhd3eb1b0_0
  - s2n=1.3.27=hdbd6064_0
  - scikit-image=0.20.0=py310h6a678d5_0
  - setuptools=68.2.2=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tifffile=2023.4.12=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.13.3=py310h22610ee_0
  - toolz=0.12.0=py310h06a4308_0
  - torchaudio=2.2.0=py310_cu118
  - torchmetrics=1.2.1=pyhd8ed1ab_0
  - torchtriton=2.2.0=py310
  - torchvision=0.17.0=py310_cu118
  - tornado=6.3.3=py310h5eee18b_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py310h06a4308_0
  - transformers=4.32.1=py310h06a4308_0
  - typing-extensions=4.9.0=py310h06a4308_1
  - typing_extensions=4.9.0=py310h06a4308_1
  - urllib3=1.26.18=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py310h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py310h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zfp=1.0.0=h6a678d5_0
  - zipp=3.17.0=py310h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - batch-face==1.4.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - decord==0.6.0
      - fonttools==4.47.2
      - grad-cam==1.5.0
      - huggingface-hub==0.20.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lime==0.2.0.1
      - llvmlite==0.42.0
      - lmdb==1.4.1
      - matplotlib==3.8.2
      - more-itertools==10.2.0
      - numba==0.59.0
      - opencv-python==4.9.0.80
      - pandas==2.2.0
      - pyparsing==3.1.1
      - pytz==2024.1
      - safetensors==0.4.2
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - shap==0.44.1
      - slicer==0.0.7
      - threadpoolctl==3.2.0
      - timm==0.9.12
      - ttach==0.0.3
      - tzdata==2023.4